- css-features/aspect-ratio.json
Hey @jonathantneal! This adds the `aspect-ratio.json` file needed to list the Aspect Ratio spec I've been working on :D
> Add Aspect Ratio spec to css-db

- tasks/start-template.html
The caniuse-lite data for some supported features have extra notes after the `y` character (e.g. for the `:matches()` CSS pseudo-class the data for Safari 9+ reports `"y #2"`, referring to the note that _except_ the _full_ support of `:matches()` these browsers _also_ support the old prefixed version). Because of the strict comparison with `'y'`, these features were reported as non-supported, which doesn't seem correct to me.
> Improve CanIUse data parsing

- cssdb.json
This feature is needed for https://github.com/jonathantneal/postcss-preset-env/issues/11
Please review it:
- I'm not sure that I choose correct `specificationId`. Because it includes [break-between](https://www.w3.org/TR/css-break-3/#break-between) and [break-within](https://www.w3.org/TR/css-break-3/#break-within) and not includes [widows-orphans](https://www.w3.org/TR/css-break-3/#widows-orphans)
- I'm not sure which `caniuse` feature chose. There are [multicolumn](https://caniuse.com/#feat=multicolumn) and [css-page-break](https://caniuse.com/#feat=css-page-break) and they both partially covers `break-`
> add break-* properties

- cssdb.json
Autoprefixer can implement most of Grid Layout properties to support old spec.
https://github.com/postcss/autoprefixer/releases/tag/7.2.0
> Postcss plugin for Grid Layout

- cssdb.json
It's now "Candidate Recommendation" https://www.w3.org/TR/mediaqueries-4/#range-context
> Updated media-query-ranage stage to 4

- cssdb.json
> The CSS Working Group just discussed `Rename :matches() to :is()`, and agreed to the following:
> * `RESOLVED: Rename :matches() to :is() and deprecate :matches() in Safari and anywhere else using it`
https://github.com/w3c/csswg-drafts/issues/3258#issuecomment-438742190
> `:matches()` was renamed to `:is()`

- cssdb.json
`ic` is a new font-relative length unit introduced at the working draft to CSS Values Module 4. I have composed a PostCSS Plugin [postcss-ic-unit](https://github.com/JLHwung/postcss-ic-unit) to polyfill `ic` to `em`.
> Add ic-unit to cssdb

- tasks/start-template.html
- tasks/style-template.css
As I was scrolling this sweet website yesterday I thought that it would be nice to have the ability to `like` the feature entries and see the demand from the community (maybe a `facebook like button` per anchored `href` or some small `google sheets` "db"). But then I realized that we already have even better data stream about css feature demand that is a Github stars badge for each polyfill which also has added benefit to encourage the user to check out the repo (at least for me, no matter the repo popularity O_o).
Anyways, here's my PR for the feature and of course feel free to change anything if you consider merging it!
- `shields.io` svg url is created inside HTML template and since we don't have Gitlab (or other) repos yet I didn't complicate the parsing.
- badge embedding comes in …
> Add github-stars-badge to feature polyfills

- tasks/style-template.css
This should fix a small styling issue.
Before:
After:
> Remove overlap

- CONTRIBUTING.md
- README.md
- STAGES.md
I've tested the links, they still work - HTTP was redirected to HTTPS already:
- https://fantasai.inkedblade.net/weblog/2011/inside-csswg/
- https://fantasai.inkedblade.net/weblog/2011/inside-csswg/process
But encourage HTTPS just a bit more :)
> Update links to use HTTPS

- src/components/caniuse-feature.astro
- src/components/feature-polyfill.astro
- src/components/feature-polyfills.astro
- src/components/feature.astro
- src/styles/style.css
Hello. Thank you for putting together this site. It's such a useful destination to learn about the new stuff in CSS!
When I was looking through it I found the links and badges below the description of each feature a bit disjointed. I think because:
- the combination of internal and external links
- the combination of badges and text links
- the preset badge is related to the polyfill listed at the bottom of the feature 
This pull request loses the badges and splits each feature into two sections:
- About
- Stage
- Title
- Description
- Example 
- Spec and Doc links (if the above info isn't enough and a person wants to learn more)
- Support
- Browsers
- Polyfills and plugins (and whether the PostCSS plugin is included in Preset Env).
It also removes the redundancy of the staging badge in …
> Split about and support information in features

- CHANGELOG.md
- cssdb.json
- cssdb.mjs
- cssdb.settings.json
- package-lock.json
- package.json
- tasks/populate-db.mjs
This adds `example` again which is needed for https://github.com/csstools/postcss-plugins/issues/176
Also removed one library from Container Queries as part of https://github.com/csstools/postcss-plugins/issues/104 and added `:has` to the mix.
> Adding example back

- cssdb.json
- cssdb.mjs
- cssdb.settings.json
- src/components/feature-polyfill.astro
* Add [`postcss-opacity-percentage`](https://github.com/mrcgrtz/postcss-opacity-percentage) as a polyfill to [cssdb.org/#opacity-percentage](https://cssdb.org/#opacity-percentage)
* Add `postcss-opacity-percentage` to the list of included plugins in `postcss-preset-env` as of [v7.3.0](https://github.com/csstools/postcss-plugins/blob/main/plugin-packs/postcss-preset-env/CHANGELOG.md#730-january-31-2022)
> Add opacity percentage polyfill

- cssdb.json
- cssdb.mjs
- cssdb.settings.json
- package-lock.json
- package.json
- utils/supported-browsers-from-mdn.mjs
This brings back `color-mix`. Introduces cascade layers and also fixes an issue in which features with flags were wrongfully showing as supported, mostly `color-contrast` but detected with `color-mix`.
> Catching up with Safari 15.4

- cssdb.json
- cssdb.mjs
- cssdb.settings.json
- package-lock.json
- package.json
- tasks/populate-db.mjs
This adds support for
* Exponential Functions (`pow()`, `sqrt()`, `hypot()`, `log()`, `exp()`):  https://www.w3.org/TR/css-values-4/#exponent-funcs
* `calc()` constants (`e`, `pi`, `infinity`, `-infinity` and `NaN`) https://www.w3.org/TR/css-values-4/#calc-constants
* Sign functions (`abs()` and `sign()`): https://www.w3.org/TR/css-values-4/#sign-funcs
* Trigonometric functions (`sin()`, `cos()`, `tan()`, `asin()`, `acos()`, `atan()` and `atan2()`): https://www.w3.org/TR/css-values-4/#trig-funcs
Needed for https://github.com/csstools/postcss-plugins/pull/356
It also allows to manually override support for things that aren't yet on MDN nor Can I Use
> New CSS features

- cssdb.json
- cssdb.mjs
- src/components/caniuse-feature.astro
- tasks/populate-db.mjs
I wanted to update the support details for `:is()` as it has a sub feature that is tracked separately : https://caniuse.com/mdn-css_selectors_is_forgiving_selector_list
When I switched support stats from caniuse to mdn (as it can track multiple features) the order of browsers changes in the output.
This made it harder to inspect the change.
----
- set a fixed 🔤 order for support details
- for the site we mimic the order from MDN
- fix some issues in the support details component
> sort browser support details

- .gitignore
- tasks/write-badges.js
see : https://github.com/postcss/postcss-media-minmax/blob/master/README.md
Fixing these is low effort and makes every plugin using these look a bit neater without requiring updates on their end.
> fix old badge urls

- CHANGELOG.md
- cssdb.json
- cssdb.mjs
- cssdb.settings.json
see : https://github.com/mdn/browser-compat-data/issues/18198
MDN data is currently outdated and no browser seems to support this.
But has been in Firefox since 78.
Weirdly it is supported in the `aspect-ratio` property in all browsers.
> `media-queries-aspect-ratio-number-values`

- cssdb.json
- cssdb.mjs
- cssdb.settings.json
MDN hasn't yet updated their tracking of this sub feature.
Adding data manually as a workaround.
> data for ratio in at-media

- CHANGELOG.md
- cssdb.json
- cssdb.mjs
- cssdb.settings.json
- package-lock.json
- package.json
https://www.w3.org/TR/css-images-4/#linear-gradients
https://deploy-preview-281--cssdb.netlify.app/#gradients-interpolation-method
> add : `gradients-interpolation-method`

- src/components/feature-polyfills.mjs
This `,` is not supposed to be there.
> fix a tiny bug in the site

- CHANGELOG.md
- cssdb.json
- cssdb.mjs
- cssdb.settings.json
- package-lock.json
We initially removed this because the firefox data is likely incorrect.
But I suggest we add it back given that Chrome and Safari shipped.
It is highly unlikely that anyone is targeting only old firefox and really needs to support a specific old firefox version while at the same time using this particular feature in a specific way that they encounter one of the bugs. So I don't think anyone will be affected by this issue.
More people will be affected from the plugin not being enabled (number of implementations) or by the plugin always transforming (targeting modern browsers)
> update support data for media-query-ranges

- cssdb.json
- cssdb.mjs
- cssdb.settings.json
- package-lock.json
Glad that I checked this :)
I somehow assumed that Firefox only had a short window where it had a partial implementation. But in reality it only shipped the full feature very recently.
https://github.com/mdn/browser-compat-data/issues/14593#issuecomment-1491436872
> more accurate data for `media-query-ranges`

- utils/baseline-data.mjs
- utils/baseline-status.mjs
- utils/release-date-for-browser-version.mjs
This doesn't have much effect now, but it is future proofing against new engines.
If we were to track something like `rgb()` then it would show `1997` + `baseline high` (a green icon). Even though Safari, Chrome and Firefox didn't exist in 1997.
> split date calc from number of implementations for baseline
